# Generated by Django 6.0 on 2026-01-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('state', models.CharField(choices=[('pradesh1', 'Koshi Pradesh'), ('pradesh2', 'Madhesh Pradesh'), ('pradesh3', 'Bagmati Pradesh'), ('pradesh4', 'Gandaki Pradesh'), ('pradesh5', 'Lumbini Pradesh'), ('pradesh6', 'Karnali Pradesh'), ('pradesh7', 'Sudurpashchim Pradesh')], max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')])),
                ('location', models.CharField()),
                ('profile_image', models.ImageField(blank=True, upload_to='pimages')),
                ('document', models.FileField(blank=True, upload_to='rdocs')),
            ],
        ),
    ]
